const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');const {pathToFileURL}=require('node:url');
const {JSDOM}=require('jsdom');const pending=require('../../site/pending-intent.js');
const root=path.resolve(__dirname,'../..'),site=path.join(root,'site');
const source=name=>fs.readFileSync(path.join(site,name),'utf8');
const tick=()=>new Promise(r=>setTimeout(r,20));
function documentFor(name){return new JSDOM(source(name).replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,''),{url:'https://test.example/'+name,runScripts:'outside-only',pretendToBeVisual:true});}
(async()=>{
 const worker=await import(pathToFileURL(path.join(root,'worker/src/index.js')));
 const config=await (await worker.default.fetch(new Request('https://test.example/api/config'),{})).json();config.sales_enabled=true;config.abacate_configured=true;
 const now=Date.now();const record={version:2,id:'fixture-intent-00001',created_at:now,tool:'jogador'};
 assert.equal(pending.valid(record,now),true);
 for(const bad of [{...record,version:1},{...record,created_at:NaN},{...record,created_at:now-7200001},{...record,created_at:now+120000},{...record,tool:'<script>'}])assert.equal(pending.valid(bad,now),false);
 const dom=documentFor('index.html'),w=dom.window;let logged=true,creates=0,requests=[],popup={location:{href:''},close(){},closed:false};
 w.RC_CONFIG={WORKER_URL:'https://test.example',PAYMENT_PROVIDER:'abacate'};
 w.RC_auth={ready:true,user:()=>logged?{uid:'fixture-user',email:'fixture@example.test',name:'Teste'}:null,getToken:()=>Promise.resolve('fixture-token'),openModal:()=>{w.authOpened=true;}};
 w.RC_entitlements={refresh:()=>Promise.resolve({active:false,plan:'free'})};
 w.open=()=>popup;w.alert=()=>{};w.matchMedia=()=>({matches:false});
 w.fetch=async(url,opts={})=>{requests.push({url,opts});if(url.endsWith('/api/config'))return new Response(JSON.stringify(config));if(url.endsWith('/api/abacate/create')){creates++;return new Response(JSON.stringify({id:'checkout_fixture',url:'https://app.abacatepay.com/pay/fixture'}));}return new Response('{}');};
 w.eval(source('tool-intents.js'));w.eval(source('pagamento.js'));w.document.dispatchEvent(new w.Event('DOMContentLoaded'));await w.RC_pay.planCatalog();await tick();
 assert.equal(typeof w.RC_pay.completeOperation,'function');assert.equal(typeof w.RC_pay.releaseOperation,'function');
 await w.RC_pay.completeOperation('fixture-op','a'.repeat(64));await w.RC_pay.releaseOperation('fixture-op');
 assert.ok(requests.some(r=>r.url.endsWith('/api/entitlements/complete')),'settlement reaches Worker');
 assert.ok(requests.some(r=>r.url.endsWith('/api/entitlements/release')),'release reaches Worker');
 assert.deepEqual(Array.from(w.document.querySelectorAll('.wf-plan-slot:not([hidden]) [data-pay]')).map(b=>b.dataset.pay),['essential7v4','pro7v4','creator30v4','studio30v4']);
 assert.equal(w.document.querySelectorAll('.wf-plan-slot').length,6);
 w.RC_pay.openPayModal('Seu mundo tem 70 MB; grátis até 10 MB.','essential7v4',{tool:'mundo',world_size_bytes:70*1048576,preserve_context:true});
 assert.equal(w.document.getElementById('payPixEmail').value,'fixture@example.test');
 assert.equal(w.document.querySelectorAll('#payModal [name=payplan]').length,4,'checkout shows every compatible plan for a fair comparison');
 assert.equal(w.document.querySelector('#payModal [name=payplan]:checked').value,'essential7v4');
 const trioRadio=w.document.querySelector('#payModal [value=pro7v4]');
 trioRadio.click();assert.equal(w.document.getElementById('payPlanPrice').textContent,'R$ 19,90');assert.match(w.document.getElementById('paySub').textContent,/12 operações/);
 assert.match(w.document.getElementById('paySub').textContent,/World Studio não incluído/);
 assert.match(w.document.querySelector('.plan-featured').textContent,/30 dias/,'month pass has a clear use period');
 w.document.querySelector('#payModal [value=essential7v4]').click();
 w.document.getElementById('payGo').click();await tick();assert.equal(creates,0,'terms prevent creation');
 w.document.getElementById('payTerms').checked=true;w.document.getElementById('payDoc').value='52998224725';w.document.getElementById('payGo').click();w.document.getElementById('payGo').click();await tick();await tick();assert.equal(creates,1,'double click creates one request');
 const body=JSON.parse(requests.find(r=>r.url.endsWith('/api/abacate/create')).opts.body);assert.equal(body.plan,'essential7v4');assert.equal(body.price_cents,undefined,'client never submits price');assert.ok(body.request_id);
 assert.equal(popup.location.href,'https://app.abacatepay.com/pay/fixture');
 w.RC_pay.openPayModal('','pro7v4',{source:'pricing_card'});
 assert.equal(w.document.querySelector('#payModal [name=payplan]:checked').value,'pro7v4','explicit Trio choice is retained');
 w.document.getElementById('payTerms').checked=true;w.document.getElementById('payDoc').value='52998224725';w.document.getElementById('payGo').click();await tick();await tick();
 const trioBody=JSON.parse(requests.filter(r=>r.url.endsWith('/api/abacate/create')).at(-1).opts.body);assert.equal(trioBody.plan,'pro7v4');assert.equal(trioBody.price_cents,undefined);
 w.RC_pay.openPayModal('','essential7v4',{tool:'mundo',world_size_bytes:200*1048576});assert.equal(w.document.querySelector('#payModal [name=payplan]:checked').value,'pro7v4','Trio handles 200 MB');
 w.RC_pay.openPayModal('','essential7v4',{tool:'mundo',world_size_bytes:301*1048576});assert.equal(w.document.querySelector('#payModal [value=pro7v4]'),null,'Pro stops above 300 MB');assert.equal(w.document.querySelector('#payModal [name=payplan]:checked').value,'creator30v4');
 w.RC_pay.openPayModal('','essential7v4',{tool:'mundo',world_size_bytes:300*1048576});assert.equal(w.document.querySelector('#payModal [name=payplan]:checked').value,'pro7v4');
 w.RC_pay.openPayModal('','essential7v4',{tool:'mundo',world_size_bytes:750*1048576+1});assert.equal(w.document.querySelector('#payModal [value=creator30v4]'),null,'5-world package stops above 300 MB');
 w.RC_pay.openPayModal('','essential7v4',{tool:'world_paint'});assert.equal(w.document.querySelector('#payModal [value=pro7v4]'),null,'Trio must not appear for Studio');
 let resolveCapacity,rejectCapacity,selectedFiles=[{name:'large.mcworld'}];
 w.WF_zip={currentFiles:()=>selectedFiles,preflight:()=>new Promise((resolve,reject)=>{resolveCapacity=resolve;rejectCapacity=reject;})};
 w.RC_pay.openPayModal('','essential7v4',{tool:'chunks'});w.document.getElementById('payTerms').checked=true;w.document.getElementById('payDoc').value='52998224725';
 const beforeCapacity=creates;w.document.getElementById('payGo').click();await tick();assert.equal(creates,beforeCapacity,'pending device preflight prevents checkout');assert.match(w.document.getElementById('payMsg').textContent,/Aguarde/);
 rejectCapacity(new Error('Memória insuficiente para este mapa'));await tick();w.document.getElementById('payGo').click();await tick();assert.equal(creates,beforeCapacity,'failed device preflight prevents payment');assert.match(w.document.getElementById('payCapacity').textContent,/Memória insuficiente/);
 w.RC_pay.openPayModal('','essential7v4',{tool:'conquistas'});resolveCapacity([{mapAllowed:false}]);await tick();assert.match(w.document.getElementById('payCapacity').textContent,/Modo leve/);
 w.document.getElementById('payTerms').checked=true;w.document.getElementById('payDoc').value='52998224725';selectedFiles=[{name:'replacement.mcworld'}];w.document.getElementById('payGo').click();await tick();assert.equal(creates,beforeCapacity,'replacement file requires a new check');
 resolveCapacity([{mapAllowed:true}]);await tick();w.document.getElementById('payGo').click();await tick();await tick();assert.equal(creates,beforeCapacity+1,'compatible file can buy after preflight');
 delete w.WF_zip;
 logged=false;w.RC_pay.checkout('pro7v4','',{tool:'builder',preserve_context:true});assert.equal(w.authOpened,true,'Google gate precedes checkout');
 dom.window.close();
 console.log('PASS: checkout catalog, account, terms, repeated click, capacity preflight and Google gate.');
})().catch(e=>{console.error(e);process.exitCode=1;});
